-- BAKKEN APP - SUPABASE DATABASE
-- Voer dit volledige script uit in Supabase -> SQL Editor.

create table if not exists public.people (
  id text primary key,
  name text not null,
  colour text not null
);

insert into public.people (id, name, colour) values
  ('person-1', 'Jonathan',  '#2563eb'),
  ('person-2', 'Samuel',   '#16a34a'),
  ('person-3', 'Jurian', '#dc2626'),
  ('person-4', 'Laurens',  '#9333ea'),
  ('person-5', 'Daniël',  '#ea580c'),
  ('person-6', 'Pablo', '#0891b2')
on conflict (id) do update
set name = excluded.name,
    colour = excluded.colour;

create table if not exists public.attempts (
  id bigint generated by default as identity primary key,
  person_id text not null references public.people(id) on delete cascade,
  time_ms integer not null check (time_ms > 0),
  created_at timestamptz not null default now()
);

create index if not exists attempts_person_time_idx
  on public.attempts(person_id, time_ms);

-- View met de beste tijd per persoon.
create or replace view public.best_times
with (security_invoker = true)
as
select
  p.id as person_id,
  p.name as person_name,
  p.colour,
  min(a.time_ms)::integer as best_time_ms
from public.people p
left join public.attempts a on a.person_id = p.id
group by p.id, p.name, p.colour
having count(a.id) > 0;

-- Row Level Security.
alter table public.people enable row level security;
alter table public.attempts enable row level security;

-- Iedereen die de website gebruikt mag personen lezen.
drop policy if exists "Anyone can read people" on public.people;
create policy "Anyone can read people"
on public.people
for select
to anon, authenticated
using (true);

-- Iedereen mag een poging toevoegen.
-- Dit is bewust zo ingesteld voor een openbare, loginloze app.
drop policy if exists "Anyone can insert attempts" on public.attempts;
create policy "Anyone can insert attempts"
on public.attempts
for insert
to anon, authenticated
with check (
  time_ms > 0
  and time_ms < 3600000
  and exists (
    select 1
    from public.people p
    where p.id = person_id
  )
);

-- Niemand mag via de publieke website pogingen aanpassen/verwijderen.
drop policy if exists "No public updates" on public.attempts;
drop policy if exists "No public deletes" on public.attempts;

-- De view moet toegankelijk zijn voor de frontend.
grant select on public.people to anon, authenticated;
grant insert on public.attempts to anon, authenticated;
grant select on public.best_times to anon, authenticated;
